# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.TextField(default='', max_length=4)),
                ('id_comentario', models.TextField(default='', max_length=4)),
                ('contenido', models.TextField(max_length=100)),
                ('fecha', models.DateField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_like', models.TextField(max_length=4)),
                ('id_proyecto', models.TextField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publicacion', models.TextField(default='', max_length=4)),
                ('id_usuario', models.TextField(default='', max_length=4)),
                ('descripcion', models.TextField(max_length=100)),
                ('foto', models.ImageField(upload_to='foto_publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.TextField(max_length=4)),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=40)),
                ('sexo', models.TextField(max_length=1)),
                ('telefono', models.TextField(max_length=8)),
                ('direccion', models.TextField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
                ('foto', models.ImageField(upload_to='foto_usuarios')),
                ('clave', models.TextField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='id_proyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_categoria',
            field=models.TextField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_usuario',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='lugar',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='objetivo',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.TextField(max_length=50),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.proyecto'),
        ),
    ]
