# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20180106_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='id_usuario',
        ),
    ]
