# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20180108_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='fecha_nac',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 8, 19, 50, 19, 953809)),
        ),
    ]
