# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 00:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_usuarios_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nac',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 0, 43, 51, 804947)),
        ),
    ]
