# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20180109_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nac',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 9, 15, 51, 333399)),
        ),
    ]
