# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 10:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20180109_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nac',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 10, 48, 35, 315234)),
        ),
    ]
